[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x568cafec3a9f5aff3629b0e9de74a78108ca6d5423fc5bbf1c43788830f4e4c4'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]